title: Mitch Torkelson
description: "Welcome to my portfolio site where I showcase my academic achievements, professional work, and ongoing projects. Dive in to learn more about my journey and expertise."
baseurl: "/flexible-jekyll"  # Adjusted to new theme's baseurl
url: "https://dinodiver.github.io"

# Author Settings
author: Mitch Torkelson
author-img: /assets/images/david-freeman.jpg  # Update the image path to your actual image
about-author: "I am a marine scientist and geospatial analyst with a deep commitment to understanding and preserving our oceanic ecosystems."
linkedin_username: mitch-torkelson
github_username: dinodiver
youtube_channel: https://www.youtube.com/user/dinodiver11
email: mitchtorkelson@gmail.com  # Optional: if you want to include an email directly

# Social Media
social-twitter: # Add your Twitter handle here
social-facebook: # Add your Facebook handle here
social-github: dinodiver
social-linkedin: mitch-torkelson
social-email: mitchtorkelson@gmail.com

# Disqus (Optional)
discus-identifier: mr-brown # Adjust to your actual Disqus identifier if you use Disqus

# Tracker
analytics: G-C4FD9YVF04  # Google Analytics

# SEO Enhancements
seo:
  twitter_card: "summary_large_image"
  og:
    type: "website"
    site_name: "Mitch Torkelson's Portfolio"

# Build Settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jemoji
  - jekyll-assets
  - jekyll-minifier

paginate: 8
paginate_path: "/page/:num"

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

favicon: "/assets/images/favicon.ico"
default_image: "/assets/images/default-share-image.png"
