title: Life of Mitch Torkelson
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my portfolio site where I showcase my academic achievements, professional work, and ongoing projects. Dive in to learn more about my journey and expertise.
permalink: ':title/'
baseurl: "/mitchtork" # the subpath of your site, e.g. /blog
url: "https://dinodiver.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: David Freeman # add your name
author-img: david-freeman.jpg # add your photo
about-author: I am a web developer focusing on front-end development. Always hungry to keep learning. # add description
social-twitter: dinodiver4 # add your Twitter handle
social-facebook: mitchtorkelson # add your Facebook handle
social-github: dinodiver # add your Github handle
social-linkedin: mitch-torkelson # add your Linkedin handle
social-email: mitchtorkelson@gmail.com # add your Email address

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
