title: Mitch Torkelson
email: mitchtorkelson@gmail.com
description: >-
  Welcome to my portfolio site. Here, I showcase my academic achievements,
  professional work, and ongoing projects. Dive in to learn more about my
  journey and expertise.
baseurl: "/mitchtorkportfolio"
url: "https://dinodiver.github.io"
linkedin_username: mitch-torkelson
github_username: dinodiver
youtube_channel: https://www.youtube.com/user/dinodiver11

# Author
author: Mitch Torkelson

# Default post image (used for social media shares)
default_image: "/assets/images/MMmtns

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate

# Google Analytics
google_analytics: G-C4FD9YVF04

# Performance and Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
