# Site settings
title: Mitch Torkelson
email: mitchtorkelson@gmail.com
description: "Welcome to my portfolio site where I showcase my academic achievements, professional work, and ongoing projects. Dive in to learn more about my journey and expertise."
baseurl: "/mitchtork" 
url: "https://dinodiver.github.io"
author: Mitch Torkelson
linkedin_username: mitch-torkelson
github_username: dinodiver
youtube_channel: https://www.youtube.com/user/dinodiver11
google_analytics: G-C4FD9YVF04
favicon: "/assets/images/favicon"
default_image: "/assets/images/default-share-image.png"

# SEO Enhancements
seo:
  twitter_card: "summary_large_image"
  og:
    type: "website"
    site_name: "Mitch Torkelson's Portfolio"

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-paginate
  - jekyll-assets
  - jekyll-minifier

# Exclusions
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
